import { Wave, User, Track, Station, Chart, ChartTrack } from '@/types';

// 목업 사용자 데이터
export const mockUsers: User[] = [
  {
    id: '1',
    email: 'alice@example.com',
    displayName: '앨리스',
    photoURL: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face',
    spotifyId: 'alice_spotify',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date(),
    followers: 245,
    following: 189,
    waveCount: 42,
    musicDNA: {
      kpop: 85,
      pop: 70,
      rock: 30,
      hiphop: 45,
      electronic: 60,
      jazz: 20,
      classical: 15,
      indie: 55,
    },
  },
  {
    id: '2',
    email: 'bob@example.com',
    displayName: '밥',
    photoURL: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    spotifyId: 'bob_spotify',
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date(),
    followers: 156,
    following: 203,
    waveCount: 38,
    musicDNA: {
      kpop: 20,
      pop: 40,
      rock: 90,
      hiphop: 75,
      electronic: 85,
      jazz: 60,
      classical: 25,
      indie: 70,
    },
  },
  {
    id: '3',
    email: 'charlie@example.com',
    displayName: '찰리',
    photoURL: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    spotifyId: 'charlie_spotify',
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date(),
    followers: 89,
    following: 134,
    waveCount: 28,
    musicDNA: {
      kpop: 95,
      pop: 80,
      rock: 25,
      hiphop: 35,
      electronic: 40,
      jazz: 30,
      classical: 20,
      indie: 50,
    },
  },
];

// 목업 트랙 데이터
export const mockTracks: Track[] = [
  {
    id: 't1',
    title: 'Dynamite',
    artist: 'BTS',
    album: 'BE',
    albumArt: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
    duration: 199,
    platform: 'spotify',
    platformId: 'spotify_dynamite',
    previewUrl: 'https://example.com/preview1.mp3',
    genre: 'K-Pop',
  },
  {
    id: 't2',
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    album: 'After Hours',
    albumArt: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
    duration: 200,
    platform: 'apple',
    platformId: 'apple_blinding',
    previewUrl: 'https://example.com/preview2.mp3',
    genre: 'Pop',
  },
  {
    id: 't3',
    title: 'Bohemian Rhapsody',
    artist: 'Queen',
    album: 'A Night at the Opera',
    albumArt: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
    duration: 355,
    platform: 'youtube',
    platformId: 'youtube_bohemian',
    previewUrl: 'https://example.com/preview3.mp3',
    genre: 'Rock',
  },
  {
    id: 't4',
    title: 'Next Level',
    artist: 'aespa',
    album: 'Next Level',
    albumArt: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
    duration: 210,
    platform: 'spotify',
    platformId: 'spotify_nextlevel',
    previewUrl: 'https://example.com/preview4.mp3',
    genre: 'K-Pop',
  },
  {
    id: 't5',
    title: 'Good 4 U',
    artist: 'Olivia Rodrigo',
    album: 'SOUR',
    albumArt: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
    duration: 178,
    platform: 'apple',
    platformId: 'apple_good4u',
    previewUrl: 'https://example.com/preview5.mp3',
    genre: 'Pop',
  },
];

// 목업 차트 트랙 데이터
export const mockChartTracks: ChartTrack[] = [
  {
    id: 'ct1',
    track: mockTracks[0],
    submittedBy: '앨리스',
    votes: 156,
    isWinner: false,
  },
  {
    id: 'ct2',
    track: mockTracks[1],
    submittedBy: '밥',
    votes: 234,
    isWinner: true,
  },
  {
    id: 'ct3',
    track: mockTracks[2],
    submittedBy: '찰리',
    votes: 89,
    isWinner: false,
  },
  {
    id: 'ct4',
    track: mockTracks[3],
    submittedBy: '앨리스',
    votes: 198,
    isWinner: false,
  },
  {
    id: 'ct5',
    track: mockTracks[4],
    submittedBy: '밥',
    votes: 145,
    isWinner: false,
  },
  // 추가 트랙들
  {
    id: 'ct6',
    track: {
      id: 't6',
      title: 'Dynamite',
      artist: 'BTS',
      album: 'Dynamite (DayTime Version)',
      albumArt: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
      genre: 'K-Pop',
      platform: 'spotify',
      platformId: 'spotify_dynamite_bt21',
      duration: 199,
    },
    submittedBy: '민지',
    votes: 312,
    isWinner: false,
  },
  {
    id: 'ct7',
    track: {
      id: 't7',
      title: 'Blinding Lights',
      artist: 'The Weeknd',
      album: 'After Hours',
      albumArt: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
      genre: 'Pop',
      platform: 'spotify',
      platformId: 'spotify_blinding_weeknd',
      duration: 200,
    },
    submittedBy: '제임스',
    votes: 178,
    isWinner: false,
  },
  {
    id: 'ct8',
    track: {
      id: 't8',
      title: 'Bohemian Rhapsody',
      artist: 'Queen',
      album: 'A Night at the Opera',
      albumArt: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
      genre: 'Rock',
      platform: 'spotify',
      platformId: 'spotify_bohemian_queen',
      duration: 354,
    },
    submittedBy: '브라이언',
    votes: 267,
    isWinner: false,
  },
  {
    id: 'ct9',
    track: {
      id: 't9',
      title: 'Hype Boy',
      artist: 'NewJeans',
      album: 'NewJeans 1st EP \'New Jeans\'',
      albumArt: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
      genre: 'K-Pop',
      platform: 'spotify',
      platformId: 'spotify_hypeboy_newjeans',
      duration: 179,
    },
    submittedBy: '하니',
    votes: 423,
    isWinner: false,
  },
  {
    id: 'ct10',
    track: {
      id: 't10',
      title: 'Shape of You',
      artist: 'Ed Sheeran',
      album: '÷ (Divide)',
      albumArt: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
      genre: 'Pop',
      platform: 'spotify',
      platformId: 'spotify_shape_edsheeran',
      duration: 233,
    },
    submittedBy: '에드',
    votes: 189,
    isWinner: false,
  },
  {
    id: 'ct11',
    track: {
      id: 't11',
      title: 'Sweet Child O\' Mine',
      artist: 'Guns N\' Roses',
      album: 'Appetite for Destruction',
      albumArt: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
      genre: 'Rock',
      platform: 'spotify',
      platformId: 'spotify_sweetchild_gnr',
      duration: 356,
    },
    submittedBy: '액슬',
    votes: 145,
    isWinner: false,
  },
  {
    id: 'ct12',
    track: {
      id: 't12',
      title: 'Super Shy',
      artist: 'NewJeans',
      album: 'NewJeans 2nd EP \'Get Up\'',
      albumArt: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
      genre: 'K-Pop',
      platform: 'spotify',
      platformId: 'spotify_supershy_newjeans',
      duration: 142,
    },
    submittedBy: '다니엘',
    votes: 356,
    isWinner: false,
  },
  {
    id: 'ct13',
    track: {
      id: 't13',
      title: 'Uptown Funk',
      artist: 'Mark Ronson ft. Bruno Mars',
      album: 'Uptown Special',
      albumArt: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
      genre: 'Pop',
      platform: 'spotify',
      platformId: 'spotify_uptown_bruno',
      duration: 270,
    },
    submittedBy: '브루노',
    votes: 234,
    isWinner: false,
  },
  {
    id: 'ct14',
    track: {
      id: 't14',
      title: 'Stairway to Heaven',
      artist: 'Led Zeppelin',
      album: 'Led Zeppelin IV',
      albumArt: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
      genre: 'Rock',
      platform: 'spotify',
      platformId: 'spotify_stairway_zeppelin',
      duration: 482,
    },
    submittedBy: '로버트',
    votes: 198,
    isWinner: false,
  },
  {
    id: 'ct15',
    track: {
      id: 't15',
      title: 'Butter',
      artist: 'BTS',
      album: 'Butter',
      albumArt: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
      genre: 'K-Pop',
      platform: 'spotify',
      platformId: 'spotify_butter_bt21',
      duration: 164,
    },
    submittedBy: '진',
    votes: 289,
    isWinner: false,
  },
];

// 목업 차트 데이터
export const mockCharts: Chart[] = [
  {
    id: 'c1',
    title: '주간 K-Pop 히트 차트',
    description: '이번 주 가장 인기 있는 K-Pop 곡들을 투표해주세요!',
    theme: 'K-Pop',
    startDate: new Date('2024-01-01'),
    endDate: new Date('2024-01-07'),
    tracks: mockChartTracks,
    isActive: true,
    winner: mockChartTracks[1],
  },
  {
    id: 'c2',
    title: '주간 팝 차트',
    description: '세계적으로 인기 있는 팝 곡들을 투표해주세요!',
    theme: 'Pop',
    startDate: new Date('2024-01-08'),
    endDate: new Date('2024-01-14'),
    tracks: mockChartTracks.slice(0, 3),
    isActive: false,
    winner: mockChartTracks[0],
  },
  {
    id: 'c3',
    title: '주간 록 차트',
    description: '클래식한 록 명곡들을 투표해주세요!',
    theme: 'Rock',
    startDate: new Date('2024-01-15'),
    endDate: new Date('2024-01-21'),
    tracks: mockChartTracks.slice(2, 5),
    isActive: false,
    winner: mockChartTracks[2],
  },
];

// 목업 스테이션 데이터
export const mockStations: Station[] = [
  {
    id: 's1',
    name: 'K-Pop Hits 2024',
    description: '최신 K-Pop 히트곡들을 모아놓은 플레이리스트입니다. BTS, BLACKPINK, NewJeans 등 인기 아티스트들의 곡들을 즐겨보세요.',
    thumbnail: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=225&fit=crop',
    youtubeChannelId: 'UC3IZKseVpdzPSBaWxBxundA',
    playlistId: 'PLFgquLnL59alCl_2TQvOiD5Vgm1hCaGSM',
    genre: 'K-Pop',
    subscriberCount: 1250000,
    isSubscribed: true,
    currentTrack: mockTracks[0],
    queue: [mockTracks[0], mockTracks[3]],
  },
  {
    id: 's2',
    name: 'Study & Focus',
    description: '공부할 때 듣기 좋은 잔잔한 음악들입니다. 집중력을 높이고 스트레스를 줄여주는 플레이리스트입니다.',
    thumbnail: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=225&fit=crop',
    youtubeChannelId: 'UC_aEa8K-EOJ3D6gOs7HcyNg',
    playlistId: 'PLofht4PTcKYnaH8w5olJCI-wUxZqX0hxr',
    genre: 'Study',
    subscriberCount: 890000,
    isSubscribed: false,
    currentTrack: undefined,
    queue: [],
  },
  {
    id: 's3',
    name: 'Workout Motivation',
    description: '운동할 때 듣기 좋은 에너지 넘치는 음악들입니다. 힘내세요!',
    thumbnail: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=225&fit=crop',
    youtubeChannelId: 'UC-9-kyTW8ZkZNDHQJ6FgpwQ',
    playlistId: 'PLofht4PTcKYnaH8w5olJCI-wUxZqX0hxr',
    genre: 'Workout',
    subscriberCount: 2100000,
    isSubscribed: true,
    currentTrack: mockTracks[1],
    queue: [mockTracks[1], mockTracks[4]],
  },
  {
    id: 's4',
    name: 'Chill Vibes',
    description: '편안한 시간을 위한 차분한 음악들입니다. 커피와 함께 즐겨보세요.',
    thumbnail: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=225&fit=crop',
    youtubeChannelId: 'UC_aEa8K-EOJ3D6gOs7HcyNg',
    playlistId: 'PLofht4PTcKYnaH8w5olJCI-wUxZqX0hxr',
    genre: 'Chill',
    subscriberCount: 567000,
    isSubscribed: false,
    currentTrack: undefined,
    queue: [],
  },
  {
    id: 's5',
    name: 'Rock Classics',
    description: '역대급 록 명곡들을 모아놓은 플레이리스트입니다. Queen, Led Zeppelin, Pink Floyd 등.',
    thumbnail: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=225&fit=crop',
    youtubeChannelId: 'UC-9-kyTW8ZkZNDHQJ6FgpwQ',
    playlistId: 'PLofht4PTcKYnaH8w5olJCI-wUxZqX0hxr',
    genre: 'Rock',
    subscriberCount: 890000,
    isSubscribed: false,
    currentTrack: mockTracks[2],
    queue: [mockTracks[2]],
  },
  {
    id: 's6',
    name: 'Jazz Lounge',
    description: '재즈 음악을 좋아하는 분들을 위한 플레이리스트입니다. 고급스러운 분위기를 연출해보세요.',
    thumbnail: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=225&fit=crop',
    youtubeChannelId: 'UC3IZKseVpdzPSBaWxBxundA',
    playlistId: 'PLFgquLnL59alCl_2TQvOiD5Vgm1hCaGSM',
    genre: 'Jazz',
    subscriberCount: 345000,
    isSubscribed: true,
    currentTrack: undefined,
    queue: [],
  },
];

// 목업 Wave 데이터
export const mockWaves: Wave[] = [
  {
    id: 'w1',
    userId: '1',
    user: mockUsers[0],
    track: mockTracks[0],
    message: '오늘 하루도 BTS와 함께! 💜',
    timestamp: new Date(Date.now() - 1000 * 60 * 5), // 5분 전
    reactions: [
      { id: 'r1', userId: '2', waveId: 'w1', type: 'like', createdAt: new Date() },
      { id: 'r2', userId: '3', waveId: 'w1', type: 'love', createdAt: new Date() },
    ],
    comments: [
      {
        id: 'c1',
        userId: '2',
        user: mockUsers[1],
        waveId: 'w1',
        content: '이 곡 정말 좋아요! 🔥',
        createdAt: new Date(Date.now() - 1000 * 60 * 2),
        reactions: [],
      },
    ],
    isPlaying: false,
  },
  {
    id: 'w2',
    userId: '2',
    user: mockUsers[1],
    track: mockTracks[1],
    message: '운동할 때 듣기 완벽한 곡이에요!',
    timestamp: new Date(Date.now() - 1000 * 60 * 15), // 15분 전
    reactions: [
      { id: 'r3', userId: '1', waveId: 'w2', type: 'fire', createdAt: new Date() },
    ],
    comments: [],
    isPlaying: true,
  },
  {
    id: 'w3',
    userId: '3',
    user: mockUsers[2],
    track: mockTracks[2],
    message: '클래식의 명곡을 다시 한번...',
    timestamp: new Date(Date.now() - 1000 * 60 * 30), // 30분 전
    reactions: [
      { id: 'r4', userId: '1', waveId: 'w3', type: 'like', createdAt: new Date() },
      { id: 'r5', userId: '2', waveId: 'w3', type: 'like', createdAt: new Date() },
      { id: 'r6', userId: '1', waveId: 'w3', type: 'love', createdAt: new Date() },
    ],
    comments: [
      {
        id: 'c2',
        userId: '1',
        user: mockUsers[0],
        waveId: 'w3',
        content: '클래식의 명곡이죠!',
        createdAt: new Date(Date.now() - 1000 * 60 * 10),
        reactions: [],
      },
      {
        id: 'c3',
        userId: '2',
        user: mockUsers[1],
        waveId: 'w3',
        content: '프레디 머큐리의 목소리가 정말...',
        createdAt: new Date(Date.now() - 1000 * 60 * 8),
        reactions: [],
      },
    ],
    isPlaying: false,
  },
  {
    id: 'w4',
    userId: '1',
    user: mockUsers[0],
    track: mockTracks[3],
    message: 'aespa 신곡 너무 좋아요!',
    timestamp: new Date(Date.now() - 1000 * 60 * 45), // 45분 전
    reactions: [
      { id: 'r7', userId: '3', waveId: 'w4', type: 'love', createdAt: new Date() },
    ],
    comments: [],
    isPlaying: false,
  },
  {
    id: 'w5',
    userId: '2',
    user: mockUsers[1],
    track: mockTracks[4],
    message: 'SOUR 앨범 전체가 다 좋아요',
    timestamp: new Date(Date.now() - 1000 * 60 * 60), // 1시간 전
    reactions: [
      { id: 'r8', userId: '1', waveId: 'w5', type: 'like', createdAt: new Date() },
      { id: 'r9', userId: '3', waveId: 'w5', type: 'fire', createdAt: new Date() },
    ],
    comments: [
      {
        id: 'c4',
        userId: '3',
        user: mockUsers[2],
        waveId: 'w5',
        content: '올리비아 로드리고 최고!',
        createdAt: new Date(Date.now() - 1000 * 60 * 30),
        reactions: [],
      },
    ],
    isPlaying: false,
  },
];

// 무한 스크롤을 위한 추가 Wave 생성 함수
export const generateMoreWaves = (page: number): Wave[] => {
  const baseTime = Date.now() - 1000 * 60 * 60 * (page + 1); // 페이지마다 1시간씩 과거
  
  const messages = [
    '오늘 기분 좋은 곡이에요!',
    '이 곡 듣고 있으면 기분이 좋아져요',
    '추천하고 싶은 곡입니다',
    '완전 내 취향이에요 💕',
    '운동할 때 듣기 좋아요',
    '공부할 때 듣는 곡이에요',
    '드라이브할 때 듣기 완벽해요',
    '새벽에 듣기 좋은 곡',
    '스트레스 해소용 음악이에요',
    '기분 전환이 필요할 때 듣는 곡',
  ];
  
  return Array.from({ length: 5 }, (_, index) => {
    const userIndex = index % mockUsers.length;
    const trackIndex = index % mockTracks.length;
    const uniqueId = `${page}_${index}_${Date.now()}`; // 고유 ID 생성
    
    return {
      id: `w${uniqueId}`,
      userId: mockUsers[userIndex].id,
      user: mockUsers[userIndex],
      track: mockTracks[trackIndex],
      message: Math.random() > 0.3 ? messages[Math.floor(Math.random() * messages.length)] : undefined,
      timestamp: new Date(baseTime - 1000 * 60 * index * 10),
      reactions: Array.from({ length: Math.floor(Math.random() * 5) }, (_, i) => ({
        id: `r${uniqueId}_${i}`,
        userId: mockUsers[(i + 1) % mockUsers.length].id,
        waveId: `w${uniqueId}`,
        type: ['like', 'love', 'fire'][Math.floor(Math.random() * 3)] as 'like' | 'love' | 'fire',
        createdAt: new Date(),
      })),
      comments: Math.random() > 0.7 ? [
        {
          id: `c${uniqueId}`,
          userId: mockUsers[(index + 1) % mockUsers.length].id,
          user: mockUsers[(index + 1) % mockUsers.length],
          waveId: `w${uniqueId}`,
          content: ['좋은 곡이네요!', '이거 완전 내 취향', '듣고 있어요 ㅎㅎ', '추천 감사합니다!'][Math.floor(Math.random() * 4)],
          createdAt: new Date(baseTime - 1000 * 60 * index * 5),
          reactions: [],
        },
      ] : [],
      isPlaying: Math.random() > 0.8,
    };
  });
};
